name: CI

on:
  push:
    branches:
      - master
      - staging
      - production

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Reconfigure git to use HTTPS
        run: >
          git config --global url."https://github.com/".insteadOf
          ssh://git@github.com/

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 20.x

      - name: Setup Expo
        uses: expo/expo-github-action@v6
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          packager: npm

      - name: Install Dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run tests
        run: npm run test:ci

      - name: Publish update
        run: eas update --auto
